#!/bin/bash

echo 'Day number:'
read day

echo "" >> README.md
echo "[Day ${day}](day${day}/README.md)" >> README.md

dayFolder="day${day}"
mkdir $dayFolder
cd $dayFolder
touch input.txt
touch sample.txt
touch README.md
cp ../_template.js index.js

echo 'Done!'
